version: "2.1"
services:
  yoinked:
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    container_name: yoinked-dev
    volumes:
      - ./../../:/app/yoinked
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: docker.io/mongo
    container_name: yoinked_mongo-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yoinked
      MONGO_INITDB_ROOT_PASSWORD: yoinked
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
