version: "2.1"
services:
  yoinked:
    build: .
    container_name: yoinked
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: docker.io/mongo
    container_name: yoinked_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yoinked
      MONGO_INITDB_ROOT_PASSWORD: yoinked
      ports:
        - 27017:27017
    volumes:
      - ./data:/data/db
