services:
  yoinked:
    build: .
    container_name: yoinked
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./yoinked.config.json:/app/yoinked/yoinked.config.json
  db:
    image: docker.io/postgres
    container_name: yoinked_postgres
    restart: always
    environment:
      POSTGRES_USER: yoinked
      POSTGRES_PASSWORD: yoinked
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
