apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - deployment.yaml
  - ingress.yaml
  - postgres.yaml
  - secret.yaml
  - service.yaml
namespace: gabe
commonLabels:
  app: shortaf
