---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-safe-browsing
  namespace: gabe
spec:
  encryptedData:
    api_key: AgCEakdA/jxiRf5rz22QcJq3FLmZt5mYbAiMOw1Yvg8yFS4iGk4/k3d+7eNXbbt/OXhPs2VtSubVB5qjv78Dd8XxKHoALHZwkZwe3A4YMfvSf9BDH8w2dwPTXTsTRoEx1LycPJvn5e0fzfaL8q74gxFpy67CsYXi10pahEqY+/aBxfvYLWyo3If0iZ7FmlGxXERz5lqIAZz9hU1lOnn9GwR6uXgpMUdBzhtw8L56N99wgmSTdPGLqydcO8iJMfFARQaBt4CBL8Iho5Oo3SCzxpxzmRned8d335ZcHlRJeysmk5j8doaLWN3NT3GbWSkHi9TgwI/GT6T1mckM1M9h4fh7ODIjjq8D1hc/cuXFkoERAtHfbdiePpqN50ziBh4J9CZQaeCuGa87aNc2yonTHNqIgtkSQNwokaIkgK2Cs7zDcuXNWSFkj0NQ1DNcA/GD0Qxb2S6XejhM8gClt8xAu6dnAVsH3Dt1vVsIa35xoHx24/tLTjXVopeRXfs6bwMqPXFLAMbrOnH0qv4l+EpuGQ4HveMzGOlMfsY1UhElG3YbCE0Vvp+jaxC/AFndAtY1kShLGEzMFDllc1ulOpYKITm7w2bSSgF1g73xIuCu53jMIW0IBN3q8nmbSfxEeHsSWLR4gFutnKycYdeTBQ2bHiS2giib5b51z+eMuPNt9u0tHb/L212DWOI5E7Nzt3f3svflN6WVqjSkNl7DILhVK6f+B82R6yR8mvbZ9umncluClADf1P84b8M=
  template:
    metadata:
      creationTimestamp: null
      name: google-safe-browsing
      namespace: gabe
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shortaf-postgres
  namespace: gabe
spec:
  encryptedData:
    password: AgAHO5+e+s6dKdaNQbwYVxZHwq2vH1JrQPgMv4+tPUqI7zv7B56agFrFjtA23atoQbLh2QXsN2BJU9VFcN6M98V99YO1NHw0sTtiqpc0CIPgDycMs889WLSbKDJHwl4+xbXef4d0HTkF+bPw4RXEXREKHzVRwd2Q6spuXZu9kmXxAJ8YiNFTYf7VwZy69lMmC3R5XYyysHUAf9jkmhG2exlAnQThP4OaQodnjtexOPg4msFlK9tRfIEUXbZXJKd2uI5eRUEDD+LvAyomcpqEfLEUB6fkierd6zJYWFP0D7ekoua7Z2rMfj57X3NgfJPxicV44vkScaw68+Q9Ssq9bcb3xopox5x3gTziae2YEKE5iZH3XIycvC/U2kDN23XU7oeMtjOoOy4RwoNo78ssY5dO1AVQL4prS8zK12ovcfqqwrH2KNfgIdvCBGN2eZHtIuBRdo+qSj8GlOC1L9AawqB3QcgKo66TnEXC1VR+6PHyXy9aqAbefzsY8jq3kSfOUT+QuOfxDg/w/30ujNRJTpxVtk9uAORKGh9+W1gvN29xwBFVJInlUnS5Rlg8kctsEGazeCaUr6mgAebM7wOc7noeE+cE+kk84C1ivbgxL1IDLgURf8uA/OKqMoqx/BEYXMdY6N2LVTjYte2JglGGiKcrO35zmr9CM+012ZQXGCLIULEU/1NVy0GTbHIP3IAnmgwzp1WomKP+tI0qyTVaE/IJT3NgZf5czCWalqyciBmSEtX2aZ30NOu1PuHqqw==
    username: AgBDpXDD6dVCBAhWG4x8uWwi2lBAOCafI6NHqIT6jh+C/0AFyOsUTdUbO6t6b4T2dLFBTRmuc0+eQUg/vRf/faXpJua8UzJ25heFP4X3aVcDhRcGrSMrpgk237YWR+p0d5K9IKWnkQwhaHqq+gVfl5fanV95T7B0TT7OLYPTd9NO/gqXGkzAloZ/LFgUnVGYPETL+u6s20dvqqKKqt1OF/XRUd800VpSWW8votxcxHtQwEyagAB1xFUR7wKK/w4uqyxpqjyLYRZfiZnr5IOjFEJn48W7dYpZAjlhrauSeJoZtSJuc2cCR2Z0mKrvQCb+PsKmjbsp1BU6HJc6RlYWv6uHnbFaRUHioAC2PniSkbJW8OQK98ldk/70VTkbJOPmYmYP459x02Ig4N9dMCizRqINczA6mmz/yhBdEbXZNMhB9sXTcJsNGucQ9NwwESZu6lESPRdwtGKSEbr5JWO2nowrkwyoeQvGSl3tAZMZ5EwmYk00HGXSu0Whn+mQQWIME/4qt7eL/16pkIHleUfAB5mFVjeghaMHVwRu3+xDbZVWuPpcQQ0u3MZkhxd2PD6MBUR9PVHeuv+zu1wvUVygB/79E42Q/wqg+5qS5/Tu7IM82R6CMNtyKAtQL6FBWGo0Rgb+M7rGn8NneKxNNCpAfqQhM7SoLZEOyNCmnE/cfpkUdDIA4clTvXNXec6LYcgykrWfbTBh+IT1
  template:
    metadata:
      creationTimestamp: null
      name: shortaf-postgres
      namespace: gabe
    type: Opaque
