name: Deploy Yoinked Container
on:
  push:
    branches:
      - '*'
env:
  DOCKER_USERNAME: robot$short.af+shortaf_gha
  NAME: short.af
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Docker Access Token
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin https://docker.super.fish
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build
        run: |-
          DOCKER_BUILDKIT=1 docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from "docker.super.fish/short.af/$NAME:latest" \
            --tag "docker.super.fish/short.af/$NAME:$GITHUB_SHA" \
            --tag "docker.super.fish/short.af/$NAME:latest" \
            .

      - name: Publish
        run: |-
          docker push "docker.super.fish/short.af/$NAME:latest" && \
          docker push "docker.super.fish/short.af/$NAME:$GITHUB_SHA"
